{{- if .Values.imageRegistryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "axiom.fullname" . }}-registry
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "axiomImagePullSecret" . }}
{{- end }}
