apiVersion: v1
kind: Secret
metadata:
  name: {{ template "axiom.fullname" . }}-secrets
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
type: Opaque
data:
  license-token: {{ .Values.licenseToken | b64enc | quote }}
  postgres-url: {{ required "Postgres URL is required!" .Values.postgresUrl | b64enc | quote }}
  redis-url: {{ .Values.redisUrl | b64enc | quote }}
  cache-registry-url: {{ .Values.cacheRegistryUrl | b64enc | quote }}
  email-url: {{ required "Email URL is required!" .Values.emailUrl | b64enc | quote }}
  storage-uri: {{ template "axiomStorageURI" .Values.storage.primary }}
  nexauth-secret: {{ randAlphaNum 16 | quote }}
  {{- if .Values.storage.fallback.uri }}
  fallback-storage-uri: {{ template "axiomStorageURI" .Values.storage.fallback }}
  {{- end }}
